# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "ci-runner"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.network "forwarded_port", guest: 80, host: 8088
  config.vm.network "forwarded_port", guest: 22, host: 8028

  config.vm.network "private_network", ip: "192.168.33.45"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/"]

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    vb.name = "runner.local"
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo curl -L --output /usr/local/bin/gitlab-runner "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64"
	sudo chmod +x /usr/local/bin/gitlab-runner
	sudo useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash
	sudo gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
	sudo gitlab-runner start
	
	sudo gitlab-runner register --non-interactive --url "http://192.168.33.44/" --registration-token "tvXgyWPjtXybV_8xhFj7" --executor "shell" \
	--description "shell-runner" --maintenance-note "Free-form maintainer notes about this runner" --tag-list "shell,aws" --run-untagged="true" \
    --locked="false" --access-level="not_protected"

  SHELL
end
